### ISSUE TITLE
ApiModel not found

### ISSUE THREAD

**Issue by xrobert35** [olivierlsc/swagger-express-ts#11] opened 2018-05-14 07:07 UTC
Hello :),

I just had the time to try what you have pushed base from my ApiModel work and something look a bit weird :) and doesn't work, from line  611 to 613

https://github.com/olivierlsc/swagger-express-ts/blob/c39d8d48fd57a658af18772522afa90888435536/src/lib/swagger-express-ts/swagger.service.ts#L611

In the common case  **args.name**  will normally be equals  to  **definitionKey**  (the class name here) and will be capitalized (like in the example "Version")  so here you add a clone of "Version" object at the "Version" index and you delete the "Version" index which doesn't work.

Perhaps you can simply add the  capitalize  line 577 `const definitionKey = target.constructor.name;` and 600 `const definitionKey = target.name;`  and remove the delete

Thanks

**Comment by olivierlsc** [comment] 2018-05-17 07:36
Hello @xrobert35 ,

I will fix the bug.

Thanks for your help.

**Comment by olivierlsc** [comment] 2018-05-17 08:30
@xrobert35 ,

I can't reproduce the bug.

Did you add "name" arg in @ApiModel ? Else you must add class name in " model" arg on all ApiOperation. You can test it with QuickStart [example-swagger-express-ts](https://github.com/olivierlsc/example-swagger-express-ts).

**Comment by xrobert35** [comment] 2018-05-17 09:16
here is my model 

`@ApiModel({
  description : "Account description" ,
  name : "Account"
})
export class Account extends MongoModel {
  @ApiModelProperty({ required : true })
  name: String;
  @ApiModelProperty({ required : true })
  email: String;
  @ApiModelProperty({ required : true })
  password: String;
  @ApiModelProperty({ required : true })
  role: Role;`

In your exemple the classe name and the args name are differente

**Comment by olivierlsc** [comment] 2018-05-17 14:16
@xrobert35,
I reproduce the error. To temporarily fix the bug, you can either delete the optional "name" argument in ApiModel or rename the class name as they have the same value.

**Comment by olivierlsc** [comment] 2018-05-19 18:48
it is fixed in the version 1.0.0-rc.4

**Closed by olivierlsc** 2018-05-19 18:48 UTC
Labels: bug
